# Generated by Django 4.1.3 on 2022-11-01 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ferretic', '0004_alter_empleado_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Ferretic.sucursal'),
        ),
    ]
