# Generated by Django 4.1.2 on 2022-11-22 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ferretic', '0005_alter_empleado_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='nombre',
        ),
    ]
