# Generated by Django 4.1.2 on 2022-11-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ferretic', '0006_remove_empleado_apellidos_remove_empleado_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
